### ISSUE TITLE
Store Front Task List

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/Maple-Morphs#1]
### Features:
- [ ] Genetics Calculator
- [ ] Order Management 
- [ ] Python Management 
- [ ] Logging to file
- [ ] Exception Handling
- [ ] Contact Form
- [ ] Two Factor Authentication
- [ ] Verifying the Account
- [ ] Forgot the Password
- [ ] Change Password
- [ ] Account Lockout 
- [ ] Reset Password
- [ ] Registering a Phone Number
- [x] Python Morphs (https://github.com/CriticalFlaw/maple_morphs/commit/37103e40b994f72f5e04f10862bbe5058c2839c2)
- [X] Guest Book (https://github.com/CriticalFlaw/maple_morphs/commit/d40ebdc6f459e6c0a840cece931c9acbf55adc66)
- [X] Checkout System (https://github.com/CriticalFlaw/maple_morphs/commit/8e3c6c6e7a4fd119972e1eb7750fd300ec40a815)
- [X] Order History (https://github.com/CriticalFlaw/maple_morphs/commit/9430a8e3df6849e6b6a4e1c7bdfca5504e63a793)
- [x] Python CRUD (https://github.com/CriticalFlaw/maple_morphs/commit/98a93d5bc3b7addb64893ff61279913ee45ff0c4)

### Bugs/Issues:
- [X] Date of Birth should not show the timestamp (https://github.com/CriticalFlaw/maple_morphs/commit/1b4bbb2cc38097cafc41bfe804825a4e179708b4)
- [X] Quantity should be deducted after purchase (https://github.com/CriticalFlaw/maple_morphs/commit/37103e40b994f72f5e04f10862bbe5058c2839c2)
